
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_3270_Duplicate = 0xfd01
XK_3270_FieldMark = 0xfd02
XK_3270_Right2 = 0xfd03
XK_3270_Left2 = 0xfd04
XK_3270_BackTab = 0xfd05
XK_3270_EraseEOF = 0xfd06
XK_3270_EraseInput = 0xfd07
XK_3270_Reset = 0xfd08
XK_3270_Quit = 0xfd09
XK_3270_PA1 = 0xfd0a
XK_3270_PA2 = 0xfd0b
XK_3270_PA3 = 0xfd0c
XK_3270_Test = 0xfd0d
XK_3270_Attn = 0xfd0e
XK_3270_CursorBlink = 0xfd0f
XK_3270_AltCursor = 0xfd10
XK_3270_KeyClick = 0xfd11
XK_3270_Jump = 0xfd12
XK_3270_Ident = 0xfd13
XK_3270_Rule = 0xfd14
XK_3270_Copy = 0xfd15
XK_3270_Play = 0xfd16
XK_3270_Setup = 0xfd17
XK_3270_Record = 0xfd18
XK_3270_ChangeScreen = 0xfd19
XK_3270_DeleteWord = 0xfd1a
XK_3270_ExSelect = 0xfd1b
XK_3270_CursorSelect = 0xfd1c
XK_3270_PrintScreen = 0xfd1d
XK_3270_Enter = 0xfd1e
