
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.


__all__ = [
	'MISCELLANY',
	'XKB_KEYS',
	'3270',
	'LATIN1',
	'LATIN2',
	'LATIN3',
	'LATIN4',
	'LATIN8',
	'LATIN9',
	'KATAKANA',
	'ARABIC',
	'CYRILLIC',
	'GREEK',
	'TECHNICAL',
	'SPECIAL',
	'PUBLISHING',
	'APL',
	'HEBREW',
	'THAI',
	'KOREAN',
	'ARMENIAN',
	'GEORGIAN',
	'CAUCASUS',
	'VIETNAMESE',
	'CURRENCY',
	'MATHEMATICAL',
	'BRAILLE',
	'SINHALA',
	'XF86',
]


from . import *


def _imp():

	dic = globals()
	groups = tuple(name for name in dic if not name.startswith('__'))
	for member in groups:
		for name in dir(dic[member]):
			if name.startswith('XK_') or name.startswith('XF86XK_'):
				dic[name] = getattr(dic[member], name)


_imp()

