
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_leftcaret = 0x0ba3
XK_rightcaret = 0x0ba6
XK_downcaret = 0x0ba8
XK_upcaret = 0x0ba9
XK_overbar = 0x0bc0
XK_downtack = 0x0bc2
XK_upshoe = 0x0bc3
XK_downstile = 0x0bc4
XK_underbar = 0x0bc6
XK_jot = 0x0bca
XK_quad = 0x0bcc
XK_uptack = 0x0bce
XK_circle = 0x0bcf
XK_upstile = 0x0bd3
XK_downshoe = 0x0bd6
XK_rightshoe = 0x0bd8
XK_leftshoe = 0x0bda
XK_lefttack = 0x0bdc
XK_righttack = 0x0bfc
