
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_Xabovedot = 0x1001e8a
XK_Ibreve = 0x100012c
XK_Zstroke = 0x10001b5
XK_Gcaron = 0x10001e6
XK_Ocaron = 0x10001d1
XK_Obarred = 0x100019f
XK_xabovedot = 0x1001e8b
XK_ibreve = 0x100012d
XK_zstroke = 0x10001b6
XK_gcaron = 0x10001e7
XK_ocaron = 0x10001d2
XK_obarred = 0x1000275
XK_SCHWA = 0x100018f
XK_schwa = 0x1000259
XK_EZH = 0x10001b7
XK_ezh = 0x1000292
XK_Lbelowdot = 0x1001e36
XK_lbelowdot = 0x1001e37
