
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_hebrew_doublelowline = 0x0cdf
XK_hebrew_aleph = 0x0ce0
XK_hebrew_bet = 0x0ce1
XK_hebrew_gimel = 0x0ce2
XK_hebrew_dalet = 0x0ce3
XK_hebrew_he = 0x0ce4
XK_hebrew_waw = 0x0ce5
XK_hebrew_zain = 0x0ce6
XK_hebrew_chet = 0x0ce7
XK_hebrew_tet = 0x0ce8
XK_hebrew_yod = 0x0ce9
XK_hebrew_finalkaph = 0x0cea
XK_hebrew_kaph = 0x0ceb
XK_hebrew_lamed = 0x0cec
XK_hebrew_finalmem = 0x0ced
XK_hebrew_mem = 0x0cee
XK_hebrew_finalnun = 0x0cef
XK_hebrew_nun = 0x0cf0
XK_hebrew_samech = 0x0cf1
XK_hebrew_ayin = 0x0cf2
XK_hebrew_finalpe = 0x0cf3
XK_hebrew_pe = 0x0cf4
XK_hebrew_finalzade = 0x0cf5
XK_hebrew_zade = 0x0cf6
XK_hebrew_qoph = 0x0cf7
XK_hebrew_resh = 0x0cf8
XK_hebrew_shin = 0x0cf9
XK_hebrew_taw = 0x0cfa
XK_Hebrew_switch = 0xff7e
