
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_Wcircumflex = 0x1000174
XK_wcircumflex = 0x1000175
XK_Ycircumflex = 0x1000176
XK_ycircumflex = 0x1000177
XK_Babovedot = 0x1001e02
XK_babovedot = 0x1001e03
XK_Dabovedot = 0x1001e0a
XK_dabovedot = 0x1001e0b
XK_Fabovedot = 0x1001e1e
XK_fabovedot = 0x1001e1f
XK_Mabovedot = 0x1001e40
XK_mabovedot = 0x1001e41
XK_Pabovedot = 0x1001e56
XK_pabovedot = 0x1001e57
XK_Sabovedot = 0x1001e60
XK_sabovedot = 0x1001e61
XK_Tabovedot = 0x1001e6a
XK_tabovedot = 0x1001e6b
XK_Wgrave = 0x1001e80
XK_wgrave = 0x1001e81
XK_Wacute = 0x1001e82
XK_wacute = 0x1001e83
XK_Wdiaeresis = 0x1001e84
XK_wdiaeresis = 0x1001e85
XK_Ygrave = 0x1001ef2
XK_ygrave = 0x1001ef3
