
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_Hstroke = 0x02a1
XK_Hcircumflex = 0x02a6
XK_Iabovedot = 0x02a9
XK_Gbreve = 0x02ab
XK_Jcircumflex = 0x02ac
XK_hstroke = 0x02b1
XK_hcircumflex = 0x02b6
XK_idotless = 0x02b9
XK_gbreve = 0x02bb
XK_jcircumflex = 0x02bc
XK_Cabovedot = 0x02c5
XK_Ccircumflex = 0x02c6
XK_Gabovedot = 0x02d5
XK_Gcircumflex = 0x02d8
XK_Ubreve = 0x02dd
XK_Scircumflex = 0x02de
XK_cabovedot = 0x02e5
XK_ccircumflex = 0x02e6
XK_gabovedot = 0x02f5
XK_gcircumflex = 0x02f8
XK_ubreve = 0x02fd
XK_scircumflex = 0x02fe
