
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_kra = 0x03a2
XK_Rcedilla = 0x03a3
XK_Itilde = 0x03a5
XK_Lcedilla = 0x03a6
XK_Emacron = 0x03aa
XK_Gcedilla = 0x03ab
XK_Tslash = 0x03ac
XK_rcedilla = 0x03b3
XK_itilde = 0x03b5
XK_lcedilla = 0x03b6
XK_emacron = 0x03ba
XK_gcedilla = 0x03bb
XK_tslash = 0x03bc
XK_ENG = 0x03bd
XK_eng = 0x03bf
XK_Amacron = 0x03c0
XK_Iogonek = 0x03c7
XK_Eabovedot = 0x03cc
XK_Imacron = 0x03cf
XK_Ncedilla = 0x03d1
XK_Omacron = 0x03d2
XK_Kcedilla = 0x03d3
XK_Uogonek = 0x03d9
XK_Utilde = 0x03dd
XK_Umacron = 0x03de
XK_amacron = 0x03e0
XK_iogonek = 0x03e7
XK_eabovedot = 0x03ec
XK_imacron = 0x03ef
XK_ncedilla = 0x03f1
XK_omacron = 0x03f2
XK_kcedilla = 0x03f3
XK_uogonek = 0x03f9
XK_utilde = 0x03fd
XK_umacron = 0x03fe
