
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_zerosuperior = 0x1002070
XK_foursuperior = 0x1002074
XK_fivesuperior = 0x1002075
XK_sixsuperior = 0x1002076
XK_sevensuperior = 0x1002077
XK_eightsuperior = 0x1002078
XK_ninesuperior = 0x1002079
XK_zerosubscript = 0x1002080
XK_onesubscript = 0x1002081
XK_twosubscript = 0x1002082
XK_threesubscript = 0x1002083
XK_foursubscript = 0x1002084
XK_fivesubscript = 0x1002085
XK_sixsubscript = 0x1002086
XK_sevensubscript = 0x1002087
XK_eightsubscript = 0x1002088
XK_ninesubscript = 0x1002089
XK_partdifferential = 0x1002202
XK_emptyset = 0x1002205
XK_elementof = 0x1002208
XK_notelementof = 0x1002209
XK_containsas = 0x100220B
XK_squareroot = 0x100221A
XK_cuberoot = 0x100221B
XK_fourthroot = 0x100221C
XK_dintegral = 0x100222C
XK_tintegral = 0x100222D
XK_because = 0x1002235
XK_approxeq = 0x1002248
XK_notapproxeq = 0x1002247
XK_notidentical = 0x1002262
XK_stricteq = 0x1002263
