
# This file is auto-generated by macpy/util/gen_x_const.py. DO NOT EDIT.

XK_blank = 0x09df
XK_soliddiamond = 0x09e0
XK_checkerboard = 0x09e1
XK_ht = 0x09e2
XK_ff = 0x09e3
XK_cr = 0x09e4
XK_lf = 0x09e5
XK_nl = 0x09e8
XK_vt = 0x09e9
XK_lowrightcorner = 0x09ea
XK_uprightcorner = 0x09eb
XK_upleftcorner = 0x09ec
XK_lowleftcorner = 0x09ed
XK_crossinglines = 0x09ee
XK_horizlinescan1 = 0x09ef
XK_horizlinescan3 = 0x09f0
XK_horizlinescan5 = 0x09f1
XK_horizlinescan7 = 0x09f2
XK_horizlinescan9 = 0x09f3
XK_leftt = 0x09f4
XK_rightt = 0x09f5
XK_bott = 0x09f6
XK_topt = 0x09f7
XK_vertbar = 0x09f8
